/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.softfriascorp.applz.modules.pay_module.views;

/**
 *
 * @author usuario
 */
public class PFiado extends javax.swing.JPanel {

    /**
     * Creates new form PFiado
     */
    public PFiado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbx_identificacion = new javax.swing.JComboBox<>();
        txt_identificacion = new javax.swing.JTextField();
        txt_nombres = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        cmbx_sexo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btn_exit = new javax.swing.JLabel();
        btn_fiar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new java.awt.GridLayout(8, 1, 0, 5));

        cmbx_identificacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cmbx_identificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIPO DE IDENTIFICACION" }));
        jPanel1.add(cmbx_identificacion);

        txt_identificacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_identificacion.setForeground(new java.awt.Color(204, 204, 204));
        txt_identificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_identificacion.setText("IDENTIFICACION");
        txt_identificacion.setBorder(null);
        jPanel1.add(txt_identificacion);

        txt_nombres.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_nombres.setForeground(new java.awt.Color(204, 204, 204));
        txt_nombres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombres.setText("NOMBRES");
        txt_nombres.setBorder(null);
        jPanel1.add(txt_nombres);

        txt_apellidos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_apellidos.setForeground(new java.awt.Color(204, 204, 204));
        txt_apellidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_apellidos.setText("APELLIDOS");
        txt_apellidos.setBorder(null);
        jPanel1.add(txt_apellidos);

        txt_direccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_direccion.setForeground(new java.awt.Color(204, 204, 204));
        txt_direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_direccion.setText("DIRECCION");
        txt_direccion.setBorder(null);
        jPanel1.add(txt_direccion);

        cmbx_sexo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cmbx_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIPO DE SEXO" }));
        jPanel1.add(cmbx_sexo);

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        btn_exit.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(255, 255, 255));
        btn_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_exit.setText("X");
        jPanel2.add(btn_exit, java.awt.BorderLayout.CENTER);

        btn_fiar.setBackground(new java.awt.Color(255, 102, 0));
        btn_fiar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_fiar.setText("FIAR");
        btn_fiar.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_fiar, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_fiar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btn_exit;
    public javax.swing.JButton btn_fiar;
    public javax.swing.JComboBox<String> cmbx_identificacion;
    public javax.swing.JComboBox<String> cmbx_sexo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField txt_apellidos;
    public javax.swing.JTextField txt_direccion;
    public javax.swing.JTextField txt_identificacion;
    public javax.swing.JTextField txt_nombres;
    // End of variables declaration//GEN-END:variables
}
