/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.softfriascorp.applz.modules.pay_module.views;

/**
 *
 * @author usuario
 */
public class PPagos extends javax.swing.JPanel {

    /**
     * Creates new form PPagos
     */
    public PPagos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_detallescompra = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Panel_totalapagar = new javax.swing.JPanel();
        txt_totalpagar = new javax.swing.JTextField();
        Panel_recibido = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_recibido = new javax.swing.JTextField();
        Panel_cambio = new javax.swing.JPanel();
        txt_cambio = new javax.swing.JTextField();
        lbl_cambioSaldoPendiente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_aceptar_pago = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btn_efectivo = new javax.swing.JButton();
        btn_nequi = new javax.swing.JButton();
        btn_tarjeta = new javax.swing.JButton();
        btn_daviplata = new javax.swing.JButton();
        btn_fiado = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btn_atras = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(832, 506));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 200));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setMinimumSize(new java.awt.Dimension(300, 0));

        txt_detallescompra.setColumns(20);
        txt_detallescompra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_detallescompra.setLineWrap(true);
        txt_detallescompra.setRows(5);
        txt_detallescompra.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txt_detallescompra.setEnabled(false);
        jScrollPane1.setViewportView(txt_detallescompra);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setMaximumSize(new java.awt.Dimension(183, 64));
        jPanel3.setMinimumSize(new java.awt.Dimension(400, 100));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TOTAL A PAGAR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = -8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(59, 12, 0, 0);
        jPanel3.add(jLabel1, gridBagConstraints);

        Panel_totalapagar.setBackground(new java.awt.Color(51, 51, 51));
        Panel_totalapagar.setForeground(new java.awt.Color(255, 255, 255));
        Panel_totalapagar.setMaximumSize(new java.awt.Dimension(183, 64));
        Panel_totalapagar.setMinimumSize(new java.awt.Dimension(100, 64));
        Panel_totalapagar.setLayout(new java.awt.BorderLayout());

        txt_totalpagar.setEditable(false);
        txt_totalpagar.setBackground(new java.awt.Color(51, 51, 51));
        txt_totalpagar.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        txt_totalpagar.setForeground(new java.awt.Color(255, 255, 255));
        txt_totalpagar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_totalpagar.setBorder(null);
        txt_totalpagar.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_totalpagar.setEnabled(false);
        txt_totalpagar.setMaximumSize(new java.awt.Dimension(1, 1));
        txt_totalpagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalpagarActionPerformed(evt);
            }
        });
        Panel_totalapagar.add(txt_totalpagar, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 212;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 10);
        jPanel3.add(Panel_totalapagar, gridBagConstraints);

        Panel_recibido.setBackground(new java.awt.Color(51, 51, 51));
        Panel_recibido.setForeground(new java.awt.Color(255, 255, 255));
        Panel_recibido.setMaximumSize(new java.awt.Dimension(183, 64));
        Panel_recibido.setMinimumSize(new java.awt.Dimension(183, 64));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("$");

        txt_recibido.setBackground(new java.awt.Color(51, 51, 51));
        txt_recibido.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        txt_recibido.setForeground(new java.awt.Color(255, 255, 255));
        txt_recibido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_recibido.setBorder(null);
        txt_recibido.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_recibido.setDisabledTextColor(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout Panel_recibidoLayout = new javax.swing.GroupLayout(Panel_recibido);
        Panel_recibido.setLayout(Panel_recibidoLayout);
        Panel_recibidoLayout.setHorizontalGroup(
            Panel_recibidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_recibidoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(txt_recibido, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
        );
        Panel_recibidoLayout.setVerticalGroup(
            Panel_recibidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txt_recibido, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 129;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 10);
        jPanel3.add(Panel_recibido, gridBagConstraints);

        Panel_cambio.setBackground(new java.awt.Color(51, 51, 51));
        Panel_cambio.setForeground(new java.awt.Color(255, 255, 255));
        Panel_cambio.setMaximumSize(new java.awt.Dimension(183, 64));
        Panel_cambio.setLayout(new java.awt.BorderLayout());

        txt_cambio.setBackground(new java.awt.Color(51, 51, 51));
        txt_cambio.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        txt_cambio.setForeground(new java.awt.Color(255, 255, 255));
        txt_cambio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cambio.setBorder(null);
        txt_cambio.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_cambio.setEnabled(false);
        txt_cambio.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        txt_cambio.setMinimumSize(new java.awt.Dimension(100, 64));
        txt_cambio.setName(""); // NOI18N
        Panel_cambio.add(txt_cambio, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 212;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 10);
        jPanel3.add(Panel_cambio, gridBagConstraints);

        lbl_cambioSaldoPendiente.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_cambioSaldoPendiente.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cambioSaldoPendiente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cambioSaldoPendiente.setText("CAMBIO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 160;
        gridBagConstraints.ipady = -8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 0);
        jPanel3.add(lbl_cambioSaldoPendiente, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RECIBIDO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 140;
        gridBagConstraints.ipady = -8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 0);
        jPanel3.add(jLabel3, gridBagConstraints);

        btn_aceptar_pago.setBackground(new java.awt.Color(0, 102, 51));
        btn_aceptar_pago.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_aceptar_pago.setForeground(new java.awt.Color(255, 255, 255));
        btn_aceptar_pago.setText("CERRAR VENTA");
        btn_aceptar_pago.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 53, 64, 0);
        jPanel3.add(btn_aceptar_pago, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setMaximumSize(new java.awt.Dimension(327, 322));
        jPanel4.setPreferredSize(new java.awt.Dimension(24, 289));
        jPanel4.setLayout(new java.awt.GridLayout(2, 1));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setName(""); // NOI18N
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.PAGE_AXIS));

        btn_efectivo.setBackground(new java.awt.Color(51, 102, 0));
        btn_efectivo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_efectivo.setForeground(new java.awt.Color(255, 255, 255));
        btn_efectivo.setText("EFECTIVO");
        btn_efectivo.setBorder(null);
        btn_efectivo.setMaximumSize(new java.awt.Dimension(327, 80));
        btn_efectivo.setMinimumSize(new java.awt.Dimension(327, 25));
        jPanel6.add(btn_efectivo);

        btn_nequi.setBackground(new java.awt.Color(102, 0, 204));
        btn_nequi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_nequi.setForeground(new java.awt.Color(255, 255, 255));
        btn_nequi.setText("NEQUI");
        btn_nequi.setBorder(null);
        btn_nequi.setMaximumSize(new java.awt.Dimension(327, 80));
        jPanel6.add(btn_nequi);

        btn_tarjeta.setBackground(new java.awt.Color(255, 204, 0));
        btn_tarjeta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_tarjeta.setForeground(new java.awt.Color(255, 255, 255));
        btn_tarjeta.setText("TARJETAS");
        btn_tarjeta.setBorder(null);
        btn_tarjeta.setMaximumSize(new java.awt.Dimension(327, 80));
        jPanel6.add(btn_tarjeta);

        btn_daviplata.setBackground(new java.awt.Color(153, 0, 51));
        btn_daviplata.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_daviplata.setForeground(new java.awt.Color(255, 255, 255));
        btn_daviplata.setText("DAVIPLATA");
        btn_daviplata.setBorder(null);
        btn_daviplata.setMaximumSize(new java.awt.Dimension(327, 80));
        jPanel6.add(btn_daviplata);

        btn_fiado.setBackground(new java.awt.Color(0, 0, 0));
        btn_fiado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_fiado.setForeground(new java.awt.Color(255, 255, 255));
        btn_fiado.setText("FIADO");
        btn_fiado.setBorder(null);
        btn_fiado.setMaximumSize(new java.awt.Dimension(327, 80));
        jPanel6.add(btn_fiado);

        jPanel4.add(jPanel6);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        btn_atras.setBackground(new java.awt.Color(102, 0, 0));
        btn_atras.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_atras.setForeground(new java.awt.Color(255, 255, 255));
        btn_atras.setText("Atras");
        btn_atras.setBorder(null);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_atras, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addComponent(btn_atras, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_totalpagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalpagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalpagarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_cambio;
    private javax.swing.JPanel Panel_recibido;
    public javax.swing.JPanel Panel_totalapagar;
    public javax.swing.JButton btn_aceptar_pago;
    public javax.swing.JButton btn_atras;
    public javax.swing.JButton btn_daviplata;
    public javax.swing.JButton btn_efectivo;
    public javax.swing.JButton btn_fiado;
    public javax.swing.JButton btn_nequi;
    public javax.swing.JButton btn_tarjeta;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lbl_cambioSaldoPendiente;
    public javax.swing.JTextField txt_cambio;
    public javax.swing.JTextArea txt_detallescompra;
    public javax.swing.JTextField txt_recibido;
    public javax.swing.JTextField txt_totalpagar;
    // End of variables declaration//GEN-END:variables
}
