/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.softfriascorp.applz.modules.inventario.views;

/**
 *
 * @author usuario
 */
public class FormAddProductos extends javax.swing.JPanel {

    /**
     * Creates new form form_addProductos
     */
    public FormAddProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmbx_categoria = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cmbx_subcategoria = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txt_codigoBarras = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_nombreProducto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_descripcionProducto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbx_unidadMedida = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txt_stock = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_cantidadIngreso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_precioProducto = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 460));

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));
        jPanel2.setLayout(new java.awt.GridLayout(19, 1, 0, 2));

        jLabel7.setText("CATEGORIA");
        jPanel2.add(jLabel7);

        cmbx_categoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbx_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE..." }));
        cmbx_categoria.setPreferredSize(null);
        jPanel2.add(cmbx_categoria);

        jLabel10.setText("SUB - CATEGORIA");
        jPanel2.add(jLabel10);

        cmbx_subcategoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbx_subcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE..." }));
        cmbx_subcategoria.setPreferredSize(null);
        jPanel2.add(cmbx_subcategoria);

        jLabel2.setText("CODIGO");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel2);

        txt_codigoBarras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_codigoBarras.setBorder(null);
        txt_codigoBarras.setPreferredSize(null);
        jPanel2.add(txt_codigoBarras);

        jLabel3.setText("NOMBRE");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel3);

        txt_nombreProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_nombreProducto.setBorder(null);
        txt_nombreProducto.setPreferredSize(null);
        jPanel2.add(txt_nombreProducto);

        jLabel5.setText("DESCRIPCION");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel5);

        txt_descripcionProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_descripcionProducto.setBorder(null);
        txt_descripcionProducto.setPreferredSize(null);
        jPanel2.add(txt_descripcionProducto);

        jLabel6.setText("UNIDAD DE MEDIDA");
        jPanel2.add(jLabel6);

        cmbx_unidadMedida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbx_unidadMedida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE..." }));
        cmbx_unidadMedida.setToolTipText("");
        cmbx_unidadMedida.setPreferredSize(null);
        jPanel2.add(cmbx_unidadMedida);

        jLabel8.setText("STOCK");
        jPanel2.add(jLabel8);

        txt_stock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_stock.setToolTipText("");
        txt_stock.setBorder(null);
        txt_stock.setPreferredSize(null);
        jPanel2.add(txt_stock);

        jLabel9.setText("CANTIDAD DE INGRESO");
        jPanel2.add(jLabel9);

        txt_cantidadIngreso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_cantidadIngreso.setToolTipText("");
        txt_cantidadIngreso.setBorder(null);
        txt_cantidadIngreso.setPreferredSize(null);
        jPanel2.add(txt_cantidadIngreso);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("PRECIO");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel4);

        txt_precioProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_precioProducto.setBorder(null);
        txt_precioProducto.setPreferredSize(null);
        jPanel2.add(txt_precioProducto);

        btn_guardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_guardar.setText("GUARDAR");
        btn_guardar.setBorder(null);
        btn_guardar.setMaximumSize(new java.awt.Dimension(109, 205));
        btn_guardar.setPreferredSize(new java.awt.Dimension(89, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_guardar;
    public javax.swing.JComboBox<String> cmbx_categoria;
    public javax.swing.JComboBox<String> cmbx_subcategoria;
    public javax.swing.JComboBox<String> cmbx_unidadMedida;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField txt_cantidadIngreso;
    public javax.swing.JTextField txt_codigoBarras;
    public javax.swing.JTextField txt_descripcionProducto;
    public javax.swing.JTextField txt_nombreProducto;
    public javax.swing.JTextField txt_precioProducto;
    public javax.swing.JTextField txt_stock;
    // End of variables declaration//GEN-END:variables
}
