/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.softfriascorp.applz.modules.inventario.views;

/**
 *
 * @author usuario
 */
public class PInventario extends javax.swing.JPanel {

    /**
     * Creates new form PInventario
     */
    public PInventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_actualizarInventario = new javax.swing.JButton();
        btn_allProducts = new javax.swing.JButton();
        btn_addProductos = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        txt_buscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        tbl_tablaInventario = new javax.swing.JTable();
        pnl_obcionesBusqueda1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pnl_obcionesBusqueda = new javax.swing.JPanel();
        cmbx_searchCategoria = new javax.swing.JComboBox<>();
        cmbx_searchSubcategorias = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        btn_stckMin = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        jSlider2 = new javax.swing.JSlider();
        btn_stckMax = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(268, 30));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(500, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(45, 30));
        jPanel1.setPreferredSize(new java.awt.Dimension(160, 30));
        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        btn_actualizarInventario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_actualizarInventario.setText("Actualizar");
        btn_actualizarInventario.setBorder(null);
        btn_actualizarInventario.setEnabled(false);
        jPanel1.add(btn_actualizarInventario);

        btn_allProducts.setBackground(new java.awt.Color(0, 153, 153));
        btn_allProducts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_allProducts.setForeground(new java.awt.Color(255, 255, 255));
        btn_allProducts.setText("ALL PRODUCTOS");
        btn_allProducts.setBorder(null);
        btn_allProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_allProductsActionPerformed(evt);
            }
        });
        jPanel1.add(btn_allProducts);

        btn_addProductos.setBackground(new java.awt.Color(204, 51, 0));
        btn_addProductos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_addProductos.setForeground(new java.awt.Color(255, 255, 255));
        btn_addProductos.setText("ADD PRODUCTOS");
        btn_addProductos.setBorder(null);
        jPanel1.add(btn_addProductos);

        jPanel2.add(jPanel1);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txt_buscar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_buscar.setForeground(new java.awt.Color(153, 153, 153));
        txt_buscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_buscar.setText("BUSCAR");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("@");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton2.setText("IMPRIMIR");

        tbl_tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ENTRY", "CODIGOBARRAS", "NOMBRE", "DESCRIPCION", "STOCK", "MEDIDA", "PRECIO", "PRECIOTOTAL"
            }
        ));
        tbl_tablaInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_tablaInventario.setShowGrid(true);
        tbl_tablaInventario.getTableHeader().setReorderingAllowed(false);
        scroll.setViewportView(tbl_tablaInventario);

        pnl_obcionesBusqueda1.setBackground(new java.awt.Color(204, 204, 204));
        pnl_obcionesBusqueda1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMaximumSize(new java.awt.Dimension(32767, 32));
        jPanel6.setLayout(new java.awt.GridLayout(1, 6, 5, 0));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("CATEGORIAS");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel6.add(jLabel13);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("SUB-CATEGORIAS");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel6.add(jLabel11);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("PROVEDOR");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel6.add(jLabel14);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("STOCK MIN");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel6.add(jLabel15);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("STOCK MAX");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel6.add(jLabel16);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel6.add(jLabel12);

        pnl_obcionesBusqueda1.add(jPanel6);

        pnl_obcionesBusqueda.setBackground(new java.awt.Color(204, 204, 204));
        pnl_obcionesBusqueda.setLayout(new java.awt.GridLayout(1, 7, 5, 0));

        cmbx_searchCategoria.setBackground(new java.awt.Color(255, 255, 255));
        cmbx_searchCategoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbx_searchCategoria.setForeground(new java.awt.Color(51, 51, 51));
        cmbx_searchCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categoria..." }));
        pnl_obcionesBusqueda.add(cmbx_searchCategoria);

        cmbx_searchSubcategorias.setBackground(new java.awt.Color(255, 255, 255));
        cmbx_searchSubcategorias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbx_searchSubcategorias.setForeground(new java.awt.Color(51, 51, 51));
        cmbx_searchSubcategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SubCategoria..." }));
        pnl_obcionesBusqueda.add(cmbx_searchSubcategorias);

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proveedor..." }));
        jComboBox3.setEnabled(false);
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        pnl_obcionesBusqueda.add(jComboBox3);

        jPanel4.setMaximumSize(new java.awt.Dimension(32809, 30));
        jPanel4.setMinimumSize(new java.awt.Dimension(78, 21));
        jPanel4.setPreferredSize(new java.awt.Dimension(242, 26));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jSlider1.setBackground(new java.awt.Color(255, 255, 255));
        jSlider1.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jSlider1.setForeground(new java.awt.Color(0, 51, 51));
        jSlider1.setMajorTickSpacing(25);
        jSlider1.setMinorTickSpacing(10);
        jSlider1.setPaintLabels(true);
        jSlider1.setValue(0);
        jSlider1.setMaximumSize(new java.awt.Dimension(32767, 40));
        jSlider1.setMinimumSize(new java.awt.Dimension(36, 16));
        jPanel4.add(jSlider1);

        btn_stckMin.setBackground(new java.awt.Color(102, 0, 51));
        btn_stckMin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_stckMin.setForeground(new java.awt.Color(255, 255, 255));
        btn_stckMin.setText("0");
        btn_stckMin.setBorder(null);
        btn_stckMin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_stckMin.setMaximumSize(new java.awt.Dimension(610, 40));
        btn_stckMin.setMinimumSize(new java.awt.Dimension(50, 15));
        btn_stckMin.setPreferredSize(new java.awt.Dimension(50, 15));
        jPanel4.add(btn_stckMin);

        pnl_obcionesBusqueda.add(jPanel4);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jSlider2.setBackground(new java.awt.Color(255, 255, 255));
        jSlider2.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jSlider2.setForeground(new java.awt.Color(0, 51, 51));
        jSlider2.setMajorTickSpacing(25);
        jSlider2.setMinorTickSpacing(10);
        jSlider2.setPaintLabels(true);
        jSlider2.setValue(0);
        jSlider2.setMaximumSize(new java.awt.Dimension(32767, 40));
        jSlider2.setMinimumSize(new java.awt.Dimension(36, 16));
        jPanel5.add(jSlider2);

        btn_stckMax.setBackground(new java.awt.Color(102, 0, 51));
        btn_stckMax.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_stckMax.setForeground(new java.awt.Color(255, 255, 255));
        btn_stckMax.setText("0");
        btn_stckMax.setBorder(null);
        btn_stckMax.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_stckMax.setMaximumSize(new java.awt.Dimension(610, 40));
        btn_stckMax.setMinimumSize(new java.awt.Dimension(50, 15));
        btn_stckMax.setPreferredSize(new java.awt.Dimension(50, 15));
        jPanel5.add(btn_stckMax);

        pnl_obcionesBusqueda.add(jPanel5);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("FILTRAR");
        jButton1.setBorder(null);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl_obcionesBusqueda.add(jButton1);

        pnl_obcionesBusqueda1.add(pnl_obcionesBusqueda);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_obcionesBusqueda1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_obcionesBusqueda1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void btn_allProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_allProductsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_allProductsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_actualizarInventario;
    public javax.swing.JToggleButton btn_addProductos;
    public javax.swing.JButton btn_allProducts;
    public javax.swing.JToggleButton btn_stckMax;
    public javax.swing.JToggleButton btn_stckMin;
    public javax.swing.JComboBox<String> cmbx_searchCategoria;
    public javax.swing.JComboBox<String> cmbx_searchSubcategorias;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    public javax.swing.JSlider jSlider1;
    public javax.swing.JSlider jSlider2;
    private javax.swing.JPanel pnl_obcionesBusqueda;
    private javax.swing.JPanel pnl_obcionesBusqueda1;
    private javax.swing.JScrollPane scroll;
    public javax.swing.JTable tbl_tablaInventario;
    public javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
