/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.softfriascorp.applz.mainframework_module.views;

/**
 *
 * @author usuario
 */
public class PMenuHeader extends javax.swing.JPanel {

    /**
     * Creates new form PMenuOptions
     */
    public PMenuHeader() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_closeApp = new javax.swing.JLabel();
        btn_menu = new javax.swing.JToggleButton();
        lbl_usuario_rol = new javax.swing.JLabel();
        lbl_updateMessage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 51));

        jPanel1.setBackground(new java.awt.Color(153, 0, 51));
        jPanel1.setLayout(new java.awt.BorderLayout());

        btn_closeApp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_closeApp.setForeground(new java.awt.Color(255, 255, 255));
        btn_closeApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_closeApp.setText("X");
        btn_closeApp.setPreferredSize(new java.awt.Dimension(15, 15));
        jPanel1.add(btn_closeApp, java.awt.BorderLayout.CENTER);

        btn_menu.setBackground(new java.awt.Color(204, 204, 204));
        btn_menu.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_menu.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu.setText("MENU");

        lbl_usuario_rol.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_usuario_rol.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario_rol.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usuario_rol.setText("User: Role");

        lbl_updateMessage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_updateMessage.setForeground(new java.awt.Color(255, 255, 255));
        lbl_updateMessage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_updateMessage.setText("v 1.0.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn_menu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_usuario_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_updateMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btn_menu)
                .addComponent(lbl_usuario_rol)
                .addComponent(lbl_updateMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btn_closeApp;
    public javax.swing.JToggleButton btn_menu;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lbl_updateMessage;
    public javax.swing.JLabel lbl_usuario_rol;
    // End of variables declaration//GEN-END:variables
}
